name: Deploy demo to GitHub Pages
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build      # creates dist/
      - run: cp -r demo site/demo/  # copy demo
      - run: cp dist/* site/   # copy built JS/CSS next to demo
      - run: cp demo/demo-redirect.html site/index.html      # root redirect → /demo/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site